version = 1

[[annotations]]
path = [
    "flake.lock",
    "nix/pg_config_wrapper.sh",
    "VERSION",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "CC0-1.0"
