# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

version = 1
SPDX-HomePage = "https://github.com/tristan957/pg_extension"
SPDX-PackageName = "pg_extension"

[[annotations]]
path = [
    "VERSION",
]
precedence = "override"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "CC0-1.0"
