# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: Tristan Partin <tristan@partin.io>

name: Builds

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.c"
      - "**.h"
      - "**.nix"
      - "**/meson.build"
      - .github/workflows/builds.yaml
      - flake.lock
      - nix/pg_config_wrapper.sh
      - VERSION
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "**.c"
      - "**.h"
      - "**.nix"
      - "**/meson.build"
      - .github/workflows/builds.yaml
      - flake.lock
      - nix/pg_config_wrapper.sh
      - VERSION

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  meson:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        buildtype: [debug, release]
        pg:
          - 14
          - 15
          - 16
          - 17
          - 18

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install --yes --no-install-recommends \
            postgresql-common ca-certificates
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install --yes --no-install-recommends \
            gcc meson ninja-build 'postgresql-server-dev-${{ matrix.pg }}'

      - name: Checkout pg_extension
        uses: actions/checkout@v7

      - name: Setup
        run: |
          meson setup build --fatal-meson-warnings --werror \
            --buildtype='${{ matrix.buildtype }}'

      - name: Build
        run: |
          ninja -C build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ${{ github.job }}-pg${{ matrix.pg }}-${{ matrix.buildtype }}
          path: |
            build/meson-logs/

  nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        pg:
          - 14
          - 15
          - 16
          - 17
          - 18

    steps:
      - name: Checkout pg_extension
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Build
        run: nix build .#postgresql_${{ matrix.pg }}
